# -*- coding: utf-8 -*-
"""2.1-i-2.2-GOD-BLESS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNOppV0OlNMWYqLBP2jNlExrpf-eo6ja
"""

import pandas as pd
import statsmodels.api as sm

data = {
    'Sila_wiatru': ['silny', 'silny', 'brak', 'brak', 'slaby', 'slaby', 'brak', 'silny', 'brak', 'silny'],
    'Zachmurzenie': ['pochmurnie', 'pochmurnie', 'slonecznie', 'slonecznie', 'pochmurnie', 'slonecznie', 'pochmurnie', 'slonecznie', 'pochmurnie', 'pochmurnie'],
    'Temperatura': ['zimno', 'cieplo', 'cieplo', 'goraco', 'goraco', 'cieplo', 'zimno', 'zimno', 'goraco', 'cieplo'],
    'Zagrano': ['nie', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'tak', 'tak']
}
df = pd.DataFrame(data)

# LABEL ENCODING
map_wiatr = {'brak': 0, 'slaby': 1, 'silny': 2}
map_chmury = {'pochmurnie': 0, 'slonecznie': 1}
map_temp = {'zimno': 0, 'cieplo': 1, 'goraco': 2}
map_zagrano = {'nie': 0, 'tak': 1}

df['Wiatr_X'] = df['Sila_wiatru'].map(map_wiatr)
df['Chmury_X'] = df['Zachmurzenie'].map(map_chmury)
df['Temp_X'] = df['Temperatura'].map(map_temp)
df['y'] = df['Zagrano'].map(map_zagrano)

X = df[['Wiatr_X', 'Chmury_X', 'Temp_X']]
X = sm.add_constant(X)
y = df['y']

model = sm.Logit(y, X).fit()
print(model.summary())

# Test - "ciepło (1), słonecznie (1), silny wiatr (2)"
# [const, Wiatr, Chmury, Temp]
nowe_dane = [1, 2, 1, 1]

prawdopodobienstwo = model.predict(nowe_dane)[0]
print(f"\nPredykcja dla (Silny, Słonecznie, Ciepło): {prawdopodobienstwo:.4f}")
print("Zagrano mecz:", "tak" if prawdopodobienstwo > 0.5 else "nie")

import pandas as pd
import statsmodels.api as sm
import importlib

klasyfikatory = importlib.import_module('Lab-3-Zadanie-1-Klasyfikatory')

dane_uczace = pd.DataFrame({
    'pieniądz':       ['nie', 'tak', 'nie', 'nie', 'tak', 'nie', 'nie', 'nie', 'nie', 'nie', 'tak', 'tak', 'nie'],
    'darmowy':        ['nie', 'tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'nie', 'tak', 'nie', 'tak'],
    'bogaty':         ['tak', 'tak', 'nie', 'nie', 'nie', 'nie', 'nie', 'nie', 'nie', 'nie', 'tak', 'nie', 'tak'],
    'nieprzyzwoicie': ['nie', 'nie', 'nie', 'nie', 'nie', 'tak', 'tak', 'tak', 'nie', 'nie', 'nie', 'nie', 'nie'],
    'tajny':          ['tak', 'nie', 'nie', 'nie', 'nie', 'tak', 'nie', 'nie', 'nie', 'tak', 'tak', 'tak', 'nie'],
    'spam':           ['tak', 'tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'tak', 'nie', 'nie', 'tak', 'tak', 'nie']
})

dane_testowe = pd.DataFrame({
    'pieniądz':       ['tak'],
    'darmowy':        ['nie'],
    'bogaty':         ['tak'],
    'nieprzyzwoicie': ['nie'],
    'tajny':          ['tak']
})

mapping = {'tak': 1, 'nie': 0}
df_logit = dane_uczace.replace(mapping)
X_test_logit = dane_testowe.replace(mapping)

X_logit = df_logit.drop('spam', axis=1)
y_logit = df_logit['spam']

X_logit = sm.add_constant(X_logit)
X_test_logit_const = sm.add_constant(X_test_logit, has_constant='add')

logit_model = sm.Logit(y_logit, X_logit).fit(disp=0)

print(logit_model.summary())

prob = logit_model.predict(X_test_logit_const)[0]
decyzja_logit = "tak" if prob > 0.5 else "nie"

print(f"Prawdopodobieństwo spamu: {prob:.4f}")
print(f"Klasyfikacja modelem logitowym: {decyzja_logit}")

print("\n\n\n")
X_train_knn = dane_uczace.drop('spam', axis=1)
y_train_knn = dane_uczace['spam']

k = 3
wynik_knn = klasyfikatory.knn(
    X_train_knn,
    y_train_knn,
    dane_testowe,
    k,
    klasyfikatory.manhattan_dist
)

klasyfikatory.print_result(dane_testowe, wynik_knn, "spam")

