# -*- coding: utf-8 -*-
"""GOD-BLESS-EGZAMIN-ROK-TEMU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAdTqGaxGaeIClfwkH8-o7mvwepyemeZ
"""

import pandas as pd
import statsmodels.api as sm
import numpy as np

df = pd.read_excel('MED-Egzamin-Zad-Podatnosc-oprogramowania.xlsx')

# 1 gdy błędy > 0, w przeciwnym razie 0.
df['Czy_blad'] = (df['Liczba bledow'] > 0).astype(int)

X = df['Numer miesiaca']
y = df['Czy_blad']

X = sm.add_constant(X)

model = sm.Logit(y, X).fit()

print(model.summary())

a0 = model.params['const']
a1 = model.params['Numer miesiaca']

print(f"\n=== WZÓR MODELU ===")
print(f"P(Y=1) = 1 / (1 + exp(-({a0:.4f} + {a1:.4f} * Miesiąc)))")

miesiac_testowy = 50
logit = a0 + a1 * miesiac_testowy
prawdopodobienstwo = 1 / (1 + np.exp(-logit))

print(f"\nPrzykładowa predykcja dla miesiąca {miesiac_testowy}:")
print(f"Prawdopodobieństwo wystąpienia błędu: {prawdopodobienstwo:.4f} (czyli {prawdopodobienstwo*100:.2f}%)")

